version: '4.17'
services:
  dev-db:
    image: postgres:15.1
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 15204008
      POSTGRES_DB: nest
    networks:
      - freecodecamp
networks:
  freecodecamp:
